// Generated by scripts/social-images/catalog.mjs. Do not edit by hand.
// prettier-ignore
export const docsPageCatalog = Object.freeze([
  {
    "page": "api-reference/index.mdx",
    "title": "API reference",
    "description": "Authenticate and call the OpenPost HTTP API.",
    "route": "/api-reference",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "api"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "api"
    }
  },
  {
    "page": "automate/api/index.mdx",
    "title": "HTTP API",
    "description": "Authenticate and make your first OpenPost API request.",
    "route": "/automate/api",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/api/media.mdx",
    "title": "Media uploads",
    "description": "Upload bytes through OpenPost's storage-safe HTTP flow.",
    "route": "/automate/api/media",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/api/publications.mdx",
    "title": "Create and publish posts",
    "description": "Create a draft, choose destination variants, and inspect delivery over HTTP.",
    "route": "/automate/api/publications",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/api/reliability.mdx",
    "title": "Revisions, retries, and jobs",
    "description": "Prevent duplicate writes and verify background publishing outcomes.",
    "route": "/automate/api/reliability",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/cli/index.mdx",
    "title": "Command-line interface",
    "description": "Install the CLI, sign in, and choose a workspace.",
    "route": "/automate/cli",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/cli/inspect-and-recover.mdx",
    "title": "Inspect and recover",
    "description": "Check publishing state, diagnose an instance, and retry failed destinations.",
    "route": "/automate/cli/inspect-and-recover",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/cli/publishing.mdx",
    "title": "Create and publish content",
    "description": "Create text, threads, media posts, and format-specific Publications from the CLI.",
    "route": "/automate/cli/publishing",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/cli/scripts-and-ci.mdx",
    "title": "Scripts and CI",
    "description": "Use stable JSON output, explicit profiles, and secret-safe authentication in automation.",
    "route": "/automate/cli/scripts-and-ci",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/index.mdx",
    "title": "Automate",
    "description": "Choose the SDK, HTTP API, CLI, or n8n for an integration.",
    "route": "/automate",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "automate"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/n8n/build-a-workflow.mdx",
    "title": "Build a publishing workflow",
    "description": "Create a draft from n8n input, validate it, and inspect delivery.",
    "route": "/automate/n8n/build-a-workflow",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/n8n/index.mdx",
    "title": "n8n workflows",
    "description": "Install the OpenPost node and test its credentials.",
    "route": "/automate/n8n",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/n8n/reliability.mdx",
    "title": "Retries and failures",
    "description": "Make n8n workflows safe to rerun and keep errors tied to their input items.",
    "route": "/automate/n8n/reliability",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/sdk/index.mdx",
    "title": "TypeScript SDK",
    "description": "Install the SDK and make your first authenticated request.",
    "route": "/automate/sdk",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/sdk/publications.mdx",
    "title": "Create and publish posts",
    "description": "Create a draft, attach media, customize variants, and inspect delivery.",
    "route": "/automate/sdk/publications",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/sdk/reliability.mdx",
    "title": "Jobs, conflicts, and errors",
    "description": "Use jobs, revisions, and typed errors to rerun SDK automation safely.",
    "route": "/automate/sdk/reliability",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "guides/accounts.mdx",
    "title": "Connect accounts",
    "description": "Add and manage social accounts in a workspace.",
    "route": "/guides/accounts",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "user-guide"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/analytics.mdx",
    "title": "Analytics",
    "description": "Understand account growth and content performance using the data your providers return.",
    "route": "/guides/analytics",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/inbox.mdx",
    "title": "Inbox and notifications",
    "description": "Read comments, reply to conversations, and choose the alerts you receive.",
    "route": "/guides/inbox",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/media-library.mdx",
    "title": "Media library",
    "description": "Upload, organize, reuse, and clean up your workspace media.",
    "route": "/guides/media-library",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/media-limits.mdx",
    "title": "Media limits",
    "description": "Default attachment limits used by OpenPost before publishing.",
    "route": "/guides/media-limits",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/publishing.mdx",
    "title": "Create and publish",
    "description": "Write, review, and publish destination-specific versions of a post.",
    "route": "/guides/publishing",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/quickstart.mdx",
    "title": "Publish your first post",
    "description": "Connect an account and publish your first OpenPost post.",
    "route": "/guides/quickstart",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "user-guide"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/scheduling.mdx",
    "title": "Schedule and calendar",
    "description": "Plan post times and recover scheduled delivery.",
    "route": "/guides/scheduling",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/screenshot-templates.mdx",
    "title": "Create a screenshot template",
    "description": "Make a conversation, receipt, or status image and add it to a post.",
    "route": "/guides/screenshot-templates",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/troubleshooting.mdx",
    "title": "Troubleshooting",
    "description": "Fix common connection, media, scheduling, and delivery problems.",
    "route": "/guides/troubleshooting",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/workspaces.mdx",
    "title": "Workspaces and settings",
    "description": "Keep accounts, content, media, and access separated by workspace.",
    "route": "/guides/workspaces",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "image-editor/color-and-effects.mdx",
    "title": "Color and effects",
    "description": "Crop images, adjust a layer or page, add effects, and remove backgrounds.",
    "route": "/image-editor/color-and-effects",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/create-a-design.mdx",
    "title": "Create a design",
    "description": "Start from a social format, template, workspace file, or post.",
    "route": "/image-editor/create-a-design",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/export-and-publish.mdx",
    "title": "Export and publish",
    "description": "Download images, save them to Media, or attach them to a post.",
    "route": "/image-editor/export-and-publish",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/index.mdx",
    "title": "Image Editor",
    "description": "Create still images and ordered carousel pages for your posts.",
    "route": "/image-editor",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "image-editor"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/layers.mdx",
    "title": "Layers",
    "description": "Add, select, arrange, group, hide, and lock design elements.",
    "route": "/image-editor/layers",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/pages-and-carousels.mdx",
    "title": "Pages and carousels",
    "description": "Create, duplicate, reorder, and export multi-page designs.",
    "route": "/image-editor/pages-and-carousels",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/saving-and-recovery.mdx",
    "title": "Saving and recovery",
    "description": "Understand browser saves, workspace autosave, conflicts, and version history.",
    "route": "/image-editor/saving-and-recovery",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/templates-and-brand.mdx",
    "title": "Templates and brand items",
    "description": "Reuse layouts, workspace colors, and custom fonts.",
    "route": "/image-editor/templates-and-brand",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "index.mdx",
    "title": "OpenPost documentation",
    "description": "Learn how to connect your accounts, create content, and check every post's delivery.",
    "route": "/",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "user-guide"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "mcp/chat-assistants.mdx",
    "title": "Chat assistants",
    "description": "Connect your assistant to OpenPost through MCP.",
    "route": "/mcp/chat-assistants",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/coding-assistants.mdx",
    "title": "Coding assistants",
    "description": "Connect your assistant to OpenPost through MCP.",
    "route": "/mcp/coding-assistants",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/index.mdx",
    "title": "AI assistants",
    "description": "Choose how an assistant connects to your OpenPost account.",
    "route": "/mcp",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "mcp"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/mcp-guide/index.mdx",
    "title": "Connect with MCP",
    "description": "Choose an endpoint, sign in, and verify assistant access.",
    "route": "/mcp/mcp-guide",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/mcp-guide/media.mdx",
    "title": "Upload media",
    "description": "Reuse workspace media or upload a public URL or local file.",
    "route": "/mcp/mcp-guide/media",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/mcp-guide/use-cases.mdx",
    "title": "Tasks and troubleshooting",
    "description": "Review schedules, create drafts, and diagnose connection or delivery failures.",
    "route": "/mcp/mcp-guide/use-cases",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/skills/index.mdx",
    "title": "Install and use the OpenPost skill",
    "description": "Give a coding assistant instructions for the OpenPost CLI.",
    "route": "/mcp/skills",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "self-hosting/ai.mdx",
    "title": "AI providers",
    "description": "Configure OpenRouter for post generation and media captions.",
    "route": "/self-hosting/ai",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/binary.mdx",
    "title": "Install from a binary",
    "description": "Run OpenPost as a single Go binary with systemd, without Docker.",
    "route": "/self-hosting/binary",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/casaos.mdx",
    "title": "Install on CasaOS",
    "description": "Import OpenPost as a CasaOS customized app from a ready-to-use Compose file.",
    "route": "/self-hosting/casaos",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/configuration.mdx",
    "title": "Configuration",
    "description": "Configure URLs, storage, provider apps, and optional self-hosted services.",
    "route": "/self-hosting/configuration",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/coolify.mdx",
    "title": "Install on Coolify",
    "description": "Deploy OpenPost on Coolify with the Git-repository Docker Compose build pack.",
    "route": "/self-hosting/coolify",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/docker-run.mdx",
    "title": "Try it with Docker run",
    "description": "Try the published Docker image locally with persistent trial data.",
    "route": "/self-hosting/docker-run",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/dockge.mdx",
    "title": "Install on Dockge",
    "description": "Manage OpenPost as a Dockge stack from the canonical Compose file.",
    "route": "/self-hosting/dockge",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/dokploy.mdx",
    "title": "Install on Dokploy",
    "description": "Deploy OpenPost on Dokploy as a Docker Compose service.",
    "route": "/self-hosting/dokploy",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/email.mdx",
    "title": "Email delivery",
    "description": "Configure authentication and notification email for self-hosted instances.",
    "route": "/self-hosting/email",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/index.mdx",
    "title": "Self-host OpenPost",
    "description": "Run OpenPost on your own server with Docker Compose.",
    "route": "/self-hosting",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "self-hosting"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/bluesky.mdx",
    "title": "Bluesky",
    "description": "Connect a Bluesky account with its handle and an app password.",
    "route": "/self-hosting/integrations/bluesky",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/discord.mdx",
    "title": "Discord",
    "description": "Connect a channel webhook or an instance-owned Discord bot.",
    "route": "/self-hosting/integrations/discord",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/facebook.mdx",
    "title": "Facebook",
    "description": "Configure Meta OAuth and connect a Facebook Page to OpenPost.",
    "route": "/self-hosting/integrations/facebook",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/index.mdx",
    "title": "Set up social integrations",
    "description": "Choose a social network, configure its credentials, and connect your first account.",
    "route": "/self-hosting/integrations",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/instagram.mdx",
    "title": "Instagram",
    "description": "Connect a Page-linked Instagram professional account through Meta OAuth.",
    "route": "/self-hosting/integrations/instagram",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/lemmy.mdx",
    "title": "Lemmy",
    "description": "Post discussions and links to Lemmy communities, then follow the conversation.",
    "route": "/self-hosting/integrations/lemmy",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/linkedin.mdx",
    "title": "LinkedIn",
    "description": "Connect LinkedIn member profiles and, with approved access, Organization Pages.",
    "route": "/self-hosting/integrations/linkedin",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/mastodon.mdx",
    "title": "Mastodon",
    "description": "Connect an account on a Mastodon server, with optional fixed app credentials.",
    "route": "/self-hosting/integrations/mastodon",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/peertube.mdx",
    "title": "PeerTube",
    "description": "Publish videos to a PeerTube channel with upload and transcoding state.",
    "route": "/self-hosting/integrations/peertube",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/piefed.mdx",
    "title": "PieFed",
    "description": "Post discussions and links to PieFed communities through its native API.",
    "route": "/self-hosting/integrations/piefed",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/pinterest.mdx",
    "title": "Pinterest",
    "description": "Configure a Pinterest app and understand the approval needed to connect and publish.",
    "route": "/self-hosting/integrations/pinterest",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/pixelfed.mdx",
    "title": "Pixelfed",
    "description": "Connect a Pixelfed instance for photo and album publishing.",
    "route": "/self-hosting/integrations/pixelfed",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/telegram.mdx",
    "title": "Telegram bot",
    "description": "Connect a Telegram channel or group to your self-hosted instance.",
    "route": "/self-hosting/integrations/telegram",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/threads.mdx",
    "title": "Threads",
    "description": "Create a Threads API app and connect a Threads account to OpenPost.",
    "route": "/self-hosting/integrations/threads",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/tiktok.mdx",
    "title": "TikTok",
    "description": "Configure TikTok Login Kit and Content Posting API for video and photo posts.",
    "route": "/self-hosting/integrations/tiktok",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/troubleshooting.mdx",
    "title": "Fix a connection",
    "description": "Fix configuration, callback, account access, and media errors.",
    "route": "/self-hosting/integrations/troubleshooting",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/x.mdx",
    "title": "X",
    "description": "Set up X OAuth 1.0a user authentication for a self-hosted instance.",
    "route": "/self-hosting/integrations/x",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/youtube.mdx",
    "title": "YouTube",
    "description": "Create a Google OAuth client and connect a YouTube channel for video uploads.",
    "route": "/self-hosting/integrations/youtube",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/maintenance.mdx",
    "title": "Maintenance",
    "description": "Back up, upgrade, monitor, and recover a self-hosted instance.",
    "route": "/self-hosting/maintenance",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/nixos.mdx",
    "title": "Install on NixOS",
    "description": "Run OpenPost on NixOS through the maintained module with sops secrets.",
    "route": "/self-hosting/nixos",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/portainer.mdx",
    "title": "Install on Portainer",
    "description": "Deploy OpenPost as a Portainer stack with environment variables entered in the UI.",
    "route": "/self-hosting/portainer",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/reverse-proxy.mdx",
    "title": "Reverse proxy and public access",
    "description": "Put OpenPost behind HTTPS so sign-in, callbacks, and media fetching work.",
    "route": "/self-hosting/reverse-proxy",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/zimaos.mdx",
    "title": "Install on ZimaOS",
    "description": "Import OpenPost as a ZimaOS custom app from a ready-to-use Compose file.",
    "route": "/self-hosting/zimaos",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "video-editor/browser-and-recovery.mdx",
    "title": "Browser support and recovery",
    "description": "Understand device limits and recover projects, sources, or exports.",
    "route": "/video-editor/browser-and-recovery",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/color-motion-and-effects.mdx",
    "title": "Color, motion, and effects",
    "description": "Change the look of a clip and animate visual layers.",
    "route": "/video-editor/color-motion-and-effects",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/export-and-publish.mdx",
    "title": "Export and publish",
    "description": "Check the render, save the file, and attach it to a post.",
    "route": "/video-editor/export-and-publish",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/index.mdx",
    "title": "Video Editor",
    "description": "Turn recordings and source clips into finished social videos.",
    "route": "/video-editor",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "video-editor"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/quick-cut-and-recorder.mdx",
    "title": "Quick Cut and Recorder",
    "description": "Trim without a full edit, or capture new source files.",
    "route": "/video-editor/quick-cut-and-recorder",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/start.mdx",
    "title": "Start a project",
    "description": "Pick a format, storage mode, and first source files.",
    "route": "/video-editor/start",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/timeline.mdx",
    "title": "Edit on the timeline",
    "description": "Arrange, trim, split, and review clips without changing the originals.",
    "route": "/video-editor/timeline",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/transcript-and-audio.mdx",
    "title": "Transcript, captions, and audio",
    "description": "Edit spoken sections, add captions, and keep speech clear.",
    "route": "/video-editor/transcript-and-audio",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "workflows/ai.mdx",
    "title": "Use AI",
    "description": "Generate text, choose a branch with AI, and inspect recorded usage.",
    "route": "/workflows/ai",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "workflows"
    }
  },
  {
    "page": "workflows/connections.mdx",
    "title": "Connections and HTTP requests",
    "description": "Save credentials, call external APIs, and handle interrupted requests.",
    "route": "/workflows/connections",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "workflows"
    }
  },
  {
    "page": "workflows/editor.mdx",
    "title": "Use the canvas",
    "description": "Add and configure steps, organize branches, and save workflow changes.",
    "route": "/workflows/editor",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "workflows"
    }
  },
  {
    "page": "workflows/examples/api-to-post.mdx",
    "title": "Turn an API response into a post",
    "description": "Read an API, format its response, and create a draft for review.",
    "route": "/workflows/examples/api-to-post",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "workflows"
    }
  },
  {
    "page": "workflows/examples/feed-digest.mdx",
    "title": "Prepare a weekly feed digest",
    "description": "Collect several feed articles into one draft for review.",
    "route": "/workflows/examples/feed-digest",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "workflows"
    }
  },
  {
    "page": "workflows/examples/relevant-releases.mdx",
    "title": "Share only relevant releases",
    "description": "Filter GitHub releases with an AI decision before drafting a post.",
    "route": "/workflows/examples/relevant-releases",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "workflows"
    }
  },
  {
    "page": "workflows/first-workflow.mdx",
    "title": "Build your first workflow",
    "description": "Create a release announcement that waits for review before publishing.",
    "route": "/workflows/first-workflow",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "workflows"
    }
  },
  {
    "page": "workflows/index.mdx",
    "title": "Workflows",
    "description": "Turn releases, feed items, and recurring tasks into posts with built-in workflows.",
    "route": "/workflows",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "workflows"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "workflows"
    }
  },
  {
    "page": "workflows/review-and-schedule.mdx",
    "title": "Review and schedule posts",
    "description": "Choose destinations, review the current post revision, and schedule approved content.",
    "route": "/workflows/review-and-schedule",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "workflows"
    }
  },
  {
    "page": "workflows/runs.mdx",
    "title": "Manage runs",
    "description": "Inspect results, resolve failures, and pause or cancel workflow work.",
    "route": "/workflows/runs",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "workflows"
    }
  },
  {
    "page": "workflows/testing.mdx",
    "title": "Preview and test",
    "description": "Understand what previews, node tests, and live runs actually do.",
    "route": "/workflows/testing",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "workflows"
    }
  },
  {
    "page": "workflows/triggers.mdx",
    "title": "Choose a trigger",
    "description": "Start workflows from releases, feed items, intervals, or OpenPost publishing events.",
    "route": "/workflows/triggers",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "workflows"
    }
  },
  {
    "page": "workflows/variables.mdx",
    "title": "Pass data between steps",
    "description": "Insert variables, inspect inputs and outputs, and transform workflow data.",
    "route": "/workflows/variables",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "workflows"
    }
  }
]);
