// Generated by scripts/social-images/catalog.mjs. Do not edit by hand.
// prettier-ignore
export const docsPageCatalog = Object.freeze([
  {
    "page": "api-reference/index.mdx",
    "title": "API reference",
    "description": "Authenticate and call the OpenPost HTTP API.",
    "route": "/api-reference",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "api"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "api"
    }
  },
  {
    "page": "automate/api/authentication.mdx",
    "title": "Authentication and workspaces",
    "description": "Create a developer token and make your first authenticated API request.",
    "route": "/automate/api/authentication",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/api/index.mdx",
    "title": "HTTP API",
    "description": "Integrate OpenPost over HTTP from any language or runtime.",
    "route": "/automate/api",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/api/media.mdx",
    "title": "Media uploads",
    "description": "Upload bytes through OpenPost's storage-safe HTTP flow.",
    "route": "/automate/api/media",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/api/publications.mdx",
    "title": "Publications and Renditions",
    "description": "Create drafts, customize destinations, and run the Publication lifecycle over HTTP.",
    "route": "/automate/api/publications",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/api/reliability.mdx",
    "title": "Revisions, retries, and jobs",
    "description": "Prevent duplicate writes and verify background publishing outcomes.",
    "route": "/automate/api/reliability",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/cli/index.mdx",
    "title": "Command-line interface",
    "description": "Control OpenPost from a shell, script, CI job, or terminal-capable agent.",
    "route": "/automate/cli",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/cli/inspect-and-recover.mdx",
    "title": "Inspect and recover",
    "description": "Check publishing state, diagnose an instance, and retry failed destinations.",
    "route": "/automate/cli/inspect-and-recover",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/cli/publishing.mdx",
    "title": "Create and publish content",
    "description": "Create text, threads, media posts, and format-specific Publications from the CLI.",
    "route": "/automate/cli/publishing",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/cli/scripts-and-ci.mdx",
    "title": "Scripts and CI",
    "description": "Use stable JSON output, explicit profiles, and secret-safe authentication in automation.",
    "route": "/automate/cli/scripts-and-ci",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/cli/setup.mdx",
    "title": "Install and sign in",
    "description": "Install the CLI, create an instance profile, authenticate, and select a workspace.",
    "route": "/automate/cli/setup",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/index.mdx",
    "title": "Automate",
    "description": "Run OpenPost from code, a shell, an agent, or a visual workflow.",
    "route": "/automate",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "automate"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/n8n/build-a-workflow.mdx",
    "title": "Build a publishing workflow",
    "description": "Turn incoming n8n items into validated and scheduled OpenPost Publications.",
    "route": "/automate/n8n/build-a-workflow",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/n8n/index.mdx",
    "title": "n8n workflows",
    "description": "Build visual OpenPost workflows with the official n8n community node.",
    "route": "/automate/n8n",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/n8n/media.mdx",
    "title": "Upload binary data",
    "description": "Send files from an n8n item to the OpenPost media library.",
    "route": "/automate/n8n/media",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/n8n/reliability.mdx",
    "title": "Retries and failures",
    "description": "Make n8n workflows safe to rerun and keep errors tied to their input items.",
    "route": "/automate/n8n/reliability",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/n8n/setup.mdx",
    "title": "Install and connect",
    "description": "Install the OpenPost community node and configure a least-privilege credential.",
    "route": "/automate/n8n/setup",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/sdk/index.mdx",
    "title": "TypeScript SDK",
    "description": "Build OpenPost scripts and services with @getopenpost/sdk.",
    "route": "/automate/sdk",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/sdk/media.mdx",
    "title": "Upload media",
    "description": "Upload files safely with the TypeScript SDK and attach them to Publications.",
    "route": "/automate/sdk/media",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/sdk/publications.mdx",
    "title": "Publications and Renditions",
    "description": "Create a draft, customize destinations, validate it, and publish it with the SDK.",
    "route": "/automate/sdk/publications",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/sdk/reliability.mdx",
    "title": "Jobs, conflicts, and errors",
    "description": "Use jobs, revisions, and typed errors to rerun SDK automation safely.",
    "route": "/automate/sdk/reliability",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/sdk/setup.mdx",
    "title": "Install and connect",
    "description": "Configure the OpenPost TypeScript SDK for Hosted or self-hosted OpenPost.",
    "route": "/automate/sdk/setup",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "automate/workflows.mdx",
    "title": "Native workflows",
    "description": "Turn releases, feed items, and published posts into repeatable content work inside OpenPost.",
    "route": "/automate/workflows",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "automate"
    }
  },
  {
    "page": "guides/accounts.mdx",
    "title": "Connect accounts",
    "description": "Add and manage social accounts in a workspace.",
    "route": "/guides/accounts",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "user-guide"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/analytics.mdx",
    "title": "Analytics",
    "description": "Understand account growth and content performance using the data your providers return.",
    "route": "/guides/analytics",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/inbox.mdx",
    "title": "Inbox and notifications",
    "description": "Read comments, reply to conversations, and choose the alerts you receive.",
    "route": "/guides/inbox",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/media-library.mdx",
    "title": "Media library",
    "description": "Upload, organize, reuse, and clean up your workspace media.",
    "route": "/guides/media-library",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/media-limits.mdx",
    "title": "Media limits",
    "description": "Default attachment limits used by OpenPost before publishing.",
    "route": "/guides/media-limits",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/media.mdx",
    "title": "Media and editors",
    "description": "Store reusable media and prepare images or video for publications.",
    "route": "/guides/media",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/publishing.mdx",
    "title": "Create and publish",
    "description": "Write, review, and publish destination-specific versions of a publication.",
    "route": "/guides/publishing",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/quickstart.mdx",
    "title": "Quickstart",
    "description": "Connect an account and publish your first OpenPost publication.",
    "route": "/guides/quickstart",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "user-guide"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/results.mdx",
    "title": "Review results",
    "description": "Find delivery status, inbox activity, and analytics.",
    "route": "/guides/results",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/scheduling.mdx",
    "title": "Schedule and calendar",
    "description": "Plan publication times and recover scheduled delivery.",
    "route": "/guides/scheduling",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/troubleshooting.mdx",
    "title": "Troubleshooting",
    "description": "Fix common connection, media, scheduling, and delivery problems.",
    "route": "/guides/troubleshooting",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/workspaces.mdx",
    "title": "Workspaces and settings",
    "description": "Keep accounts, content, media, and access separated by workspace.",
    "route": "/guides/workspaces",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "image-editor/color-and-effects.mdx",
    "title": "Color and effects",
    "description": "Crop images, adjust a layer or page, add effects, and remove backgrounds.",
    "route": "/image-editor/color-and-effects",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/create-a-design.mdx",
    "title": "Create a design",
    "description": "Start from a social format, template, workspace file, or post.",
    "route": "/image-editor/create-a-design",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/editor-layout.mdx",
    "title": "Editor layout",
    "description": "Find the canvas, tools, properties, layers, and page controls.",
    "route": "/image-editor/editor-layout",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/export-and-publish.mdx",
    "title": "Export and publish",
    "description": "Download images, save them to Media, or attach them to a post.",
    "route": "/image-editor/export-and-publish",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/index.mdx",
    "title": "Image Editor",
    "description": "Create still images and ordered carousel pages for your posts.",
    "route": "/image-editor",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "image-editor"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/layers.mdx",
    "title": "Layers",
    "description": "Add, select, arrange, group, hide, and lock design elements.",
    "route": "/image-editor/layers",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/limits.mdx",
    "title": "Limits",
    "description": "Check what Image Editor supports and where to use another tool.",
    "route": "/image-editor/limits",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/pages-and-carousels.mdx",
    "title": "Pages and carousels",
    "description": "Create, duplicate, reorder, and export multi-page designs.",
    "route": "/image-editor/pages-and-carousels",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/saving-and-recovery.mdx",
    "title": "Saving and recovery",
    "description": "Understand browser saves, workspace autosave, conflicts, and version history.",
    "route": "/image-editor/saving-and-recovery",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "image-editor/templates-and-brand.mdx",
    "title": "Templates and brand items",
    "description": "Reuse layouts, workspace colors, and custom fonts.",
    "route": "/image-editor/templates-and-brand",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "image-editor"
    }
  },
  {
    "page": "index.mdx",
    "title": "OpenPost documentation",
    "description": "Learn how to connect your accounts, create content, and check every post's delivery.",
    "route": "/",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "user-guide"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "mcp/antigravity.mdx",
    "title": "Connect Antigravity",
    "description": "Use the OpenPost local bridge from Antigravity.",
    "route": "/mcp/antigravity",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/chatgpt.mdx",
    "title": "Connect ChatGPT",
    "description": "Connect OpenPost's MCP server to ChatGPT for schedule reviews and drafts.",
    "route": "/mcp/chatgpt",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/choose-an-agent-connection.mdx",
    "title": "Choose an agent connection",
    "description": "Compare MCP, the OpenPost CLI skill, and direct CLI commands.",
    "route": "/mcp/choose-an-agent-connection",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/claude-code.mdx",
    "title": "Connect Claude Code",
    "description": "Use OpenPost from Claude Code in your terminal.",
    "route": "/mcp/claude-code",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/claude-desktop.mdx",
    "title": "Connect Claude Desktop",
    "description": "Connect through Claude account settings or a local OpenPost bridge.",
    "route": "/mcp/claude-desktop",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/claude.mdx",
    "title": "Connect Claude web",
    "description": "Connect OpenPost to Claude through a custom connector.",
    "route": "/mcp/claude",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/codex.mdx",
    "title": "Connect Codex",
    "description": "Add OpenPost to Codex with remote MCP and browser sign-in.",
    "route": "/mcp/codex",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/cursor.mdx",
    "title": "Connect Cursor",
    "description": "Add OpenPost to Cursor using remote MCP and OAuth.",
    "route": "/mcp/cursor",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/devin.mdx",
    "title": "Connect Devin",
    "description": "Give Devin access to your OpenPost workspace through MCP.",
    "route": "/mcp/devin",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/gemini-cli.mdx",
    "title": "Connect Gemini CLI",
    "description": "Review and prepare OpenPost posts from Gemini CLI.",
    "route": "/mcp/gemini-cli",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/github-copilot.mdx",
    "title": "Connect GitHub Copilot",
    "description": "Use OpenPost from Copilot agent chat in VS Code.",
    "route": "/mcp/github-copilot",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/grok.mdx",
    "title": "Connect Grok",
    "description": "Add OpenPost as a custom Grok connector.",
    "route": "/mcp/grok",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/hermes.mdx",
    "title": "Connect Hermes Agent",
    "description": "Add OpenPost to Hermes Agent as an OAuth MCP server.",
    "route": "/mcp/hermes",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/index.mdx",
    "title": "AI assistants",
    "description": "Choose how an AI assistant should work with OpenPost.",
    "route": "/mcp",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "mcp"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/mcp-guide/endpoints-and-tools.mdx",
    "title": "Endpoints and tools",
    "description": "Choose OpenPost's direct or compact MCP tool list.",
    "route": "/mcp/mcp-guide/endpoints-and-tools",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/mcp-guide/index.mdx",
    "title": "Connect with MCP",
    "description": "Give an AI assistant access to OpenPost through MCP.",
    "route": "/mcp/mcp-guide",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/mcp-guide/media.mdx",
    "title": "Media and local files",
    "description": "Give an MCP assistant existing media, a public URL, or a local file.",
    "route": "/mcp/mcp-guide/media",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/mcp-guide/permissions-and-safety.mdx",
    "title": "Permissions and safety",
    "description": "Limit an MCP connection to the access an assistant needs.",
    "route": "/mcp/mcp-guide/permissions-and-safety",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/mcp-guide/self-hosted-and-local.mdx",
    "title": "Self-hosted and local connections",
    "description": "Connect an MCP client to a public or private OpenPost instance.",
    "route": "/mcp/mcp-guide/self-hosted-and-local",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/mcp-guide/use-cases.mdx",
    "title": "MCP use cases",
    "description": "Use MCP for schedule reviews, drafts, publishing, and delivery checks.",
    "route": "/mcp/mcp-guide/use-cases",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/openclaw.mdx",
    "title": "Connect OpenClaw",
    "description": "Connect an OpenClaw agent to your OpenPost workspace.",
    "route": "/mcp/openclaw",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/opencode.mdx",
    "title": "Connect OpenCode",
    "description": "Add OpenPost to OpenCode using remote MCP and OAuth.",
    "route": "/mcp/opencode",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/perplexity.mdx",
    "title": "Connect Perplexity",
    "description": "Use OpenPost through a custom remote Perplexity connector.",
    "route": "/mcp/perplexity",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/skills/index.mdx",
    "title": "OpenPost skills",
    "description": "Give a compatible coding assistant OpenPost operating guidance.",
    "route": "/mcp/skills",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/skills/install.mdx",
    "title": "Install the OpenPost skill",
    "description": "Install the openpost CLI and its Agent Skill.",
    "route": "/mcp/skills/install",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/skills/openpost-cli.mdx",
    "title": "How the CLI skill works",
    "description": "Understand the workflow and limits of the openpost-cli skill.",
    "route": "/mcp/skills/openpost-cli",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/skills/use-cases.mdx",
    "title": "CLI skill use cases",
    "description": "Use the openpost-cli skill for inspection, drafts, publishing, and recovery.",
    "route": "/mcp/skills/use-cases",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/vs-code.mdx",
    "title": "Connect VS Code",
    "description": "Use OpenPost tools in VS Code agent chat.",
    "route": "/mcp/vs-code",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "self-hosting/ai.mdx",
    "title": "AI providers",
    "description": "Configure OpenRouter for post generation and media captions.",
    "route": "/self-hosting/ai",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/binary.mdx",
    "title": "Install from a binary",
    "description": "Run OpenPost as a single Go binary with systemd, without Docker.",
    "route": "/self-hosting/binary",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/casaos.mdx",
    "title": "Install on CasaOS",
    "description": "Import OpenPost as a CasaOS customized app from a ready-to-use Compose file.",
    "route": "/self-hosting/casaos",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/configuration.mdx",
    "title": "Configuration",
    "description": "Configure URLs, storage, provider apps, and optional self-hosted services.",
    "route": "/self-hosting/configuration",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/coolify.mdx",
    "title": "Install on Coolify",
    "description": "Deploy OpenPost on Coolify with the Git-repository Docker Compose build pack.",
    "route": "/self-hosting/coolify",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/docker-run.mdx",
    "title": "Try it with Docker run",
    "description": "A one-line throwaway test of the published image.",
    "route": "/self-hosting/docker-run",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/dockge.mdx",
    "title": "Install on Dockge",
    "description": "Manage OpenPost as a Dockge stack from the canonical Compose file.",
    "route": "/self-hosting/dockge",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/dokploy.mdx",
    "title": "Install on Dokploy",
    "description": "Deploy OpenPost on Dokploy as a Docker Compose service.",
    "route": "/self-hosting/dokploy",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/email.mdx",
    "title": "Email delivery",
    "description": "Configure authentication and notification email for self-hosted instances.",
    "route": "/self-hosting/email",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/index.mdx",
    "title": "Self-host OpenPost",
    "description": "Run OpenPost on your own server with Docker Compose.",
    "route": "/self-hosting",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "self-hosting"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/bluesky.mdx",
    "title": "Bluesky",
    "description": "Connect a Bluesky account with its handle and an app password.",
    "route": "/self-hosting/integrations/bluesky",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/discord.mdx",
    "title": "Discord",
    "description": "Connect a channel webhook or an instance-owned Discord bot.",
    "route": "/self-hosting/integrations/discord",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/facebook.mdx",
    "title": "Facebook",
    "description": "Configure Meta OAuth and connect a Facebook Page to OpenPost.",
    "route": "/self-hosting/integrations/facebook",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/index.mdx",
    "title": "Set up social integrations",
    "description": "Choose a social network, configure its credentials, and connect your first account.",
    "route": "/self-hosting/integrations",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/instagram.mdx",
    "title": "Instagram",
    "description": "Connect a Page-linked Instagram professional account through Meta OAuth.",
    "route": "/self-hosting/integrations/instagram",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/lemmy.mdx",
    "title": "Lemmy",
    "description": "Post discussions and links to Lemmy communities, then follow the conversation.",
    "route": "/self-hosting/integrations/lemmy",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/linkedin.mdx",
    "title": "LinkedIn",
    "description": "Connect LinkedIn member profiles and, with approved access, Organization Pages.",
    "route": "/self-hosting/integrations/linkedin",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/mastodon.mdx",
    "title": "Mastodon",
    "description": "Connect an account on a Mastodon server, with optional fixed app credentials.",
    "route": "/self-hosting/integrations/mastodon",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/peertube.mdx",
    "title": "PeerTube",
    "description": "Publish videos to a PeerTube channel with upload and transcoding state.",
    "route": "/self-hosting/integrations/peertube",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/piefed.mdx",
    "title": "PieFed",
    "description": "Post discussions and links to PieFed communities through its native API.",
    "route": "/self-hosting/integrations/piefed",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/pinterest.mdx",
    "title": "Pinterest",
    "description": "Configure a Pinterest app and understand the approval needed to connect and publish.",
    "route": "/self-hosting/integrations/pinterest",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/pixelfed.mdx",
    "title": "Pixelfed",
    "description": "Connect a Pixelfed instance for photo and album publishing.",
    "route": "/self-hosting/integrations/pixelfed",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/telegram.mdx",
    "title": "Telegram bot",
    "description": "Connect a Telegram channel or group to your self-hosted instance.",
    "route": "/self-hosting/integrations/telegram",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/threads.mdx",
    "title": "Threads",
    "description": "Create a Threads API app and connect a Threads account to OpenPost.",
    "route": "/self-hosting/integrations/threads",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/tiktok.mdx",
    "title": "TikTok",
    "description": "Configure TikTok Login Kit and Content Posting API for video and photo posts.",
    "route": "/self-hosting/integrations/tiktok",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/troubleshooting.mdx",
    "title": "Fix a connection",
    "description": "Diagnose callback errors, missing accounts, app permissions, and media access during setup.",
    "route": "/self-hosting/integrations/troubleshooting",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/x.mdx",
    "title": "X",
    "description": "Set up X OAuth 1.0a user authentication for a self-hosted instance.",
    "route": "/self-hosting/integrations/x",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/youtube.mdx",
    "title": "YouTube",
    "description": "Create a Google OAuth client and connect a YouTube channel for video uploads.",
    "route": "/self-hosting/integrations/youtube",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/maintenance.mdx",
    "title": "Maintenance",
    "description": "Back up, upgrade, monitor, and recover a self-hosted instance.",
    "route": "/self-hosting/maintenance",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/nixos.mdx",
    "title": "Install on NixOS",
    "description": "Run OpenPost on NixOS through the maintained module with sops secrets.",
    "route": "/self-hosting/nixos",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/portainer.mdx",
    "title": "Install on Portainer",
    "description": "Deploy OpenPost as a Portainer stack with environment variables entered in the UI.",
    "route": "/self-hosting/portainer",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/reverse-proxy.mdx",
    "title": "Reverse proxy and public access",
    "description": "Put OpenPost behind HTTPS so sign-in, callbacks, and media fetching work.",
    "route": "/self-hosting/reverse-proxy",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/zimaos.mdx",
    "title": "Install on ZimaOS",
    "description": "Import OpenPost as a ZimaOS custom app from a ready-to-use Compose file.",
    "route": "/self-hosting/zimaos",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "video-editor/browser-and-recovery.mdx",
    "title": "Browser support and recovery",
    "description": "Understand device limits and recover projects, sources, or exports.",
    "route": "/video-editor/browser-and-recovery",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/color-motion-and-effects.mdx",
    "title": "Color, motion, and effects",
    "description": "Change the look of a clip and animate visual layers.",
    "route": "/video-editor/color-motion-and-effects",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/export-and-publish.mdx",
    "title": "Export and publish",
    "description": "Check the render, save the file, and attach it to a publication.",
    "route": "/video-editor/export-and-publish",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/index.mdx",
    "title": "Video Editor",
    "description": "Turn recordings and source clips into finished social videos.",
    "route": "/video-editor",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "video-editor"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/projects-and-storage.mdx",
    "title": "Projects and storage",
    "description": "Choose cloud or local storage without losing track of your originals.",
    "route": "/video-editor/projects-and-storage",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/quick-cut-and-recorder.mdx",
    "title": "Quick Cut and Recorder",
    "description": "Trim without a full edit, or capture new source files.",
    "route": "/video-editor/quick-cut-and-recorder",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/start.mdx",
    "title": "Start a project",
    "description": "Pick a format, storage mode, and first source files.",
    "route": "/video-editor/start",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/timeline.mdx",
    "title": "Edit on the timeline",
    "description": "Arrange, trim, split, and review clips without changing the originals.",
    "route": "/video-editor/timeline",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  },
  {
    "page": "video-editor/transcript-and-audio.mdx",
    "title": "Transcript, captions, and audio",
    "description": "Edit spoken sections, add captions, and keep speech clear.",
    "route": "/video-editor/transcript-and-audio",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "video-editor"
    }
  }
]);
