package handlers

import (
	"context"
	"net/http"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/openpost/backend/internal/diagnostics"
)

// maxIngestRequestBytes caps a single cross-instance report. Reports are
// metadata only; anything larger is rejected before decoding.
const maxIngestRequestBytes = 16 << 10

// Huma treats reaching MaxBodyBytes as oversized, so add one byte to keep the
// application limit inclusive.
const maxIngestHumaBodyBytes = maxIngestRequestBytes + 1

// IngestHandler serves the official cross-instance diagnostics receiver.
// Unlike the instance-local report endpoint, this route is unauthenticated:
// reporting installations have no account on the receiving instance.
// Protection comes from strict schema validation, tight quotas, and the
// operator-owned enable switch, not from caller identity. Incoming reports
// are untrusted; only the allowlisted envelope may reach Discord, and the
// webhook URL itself never leaves the server environment.
type IngestHandler struct {
	ingester *diagnostics.Ingester
}

func NewIngestHandler(ingester *diagnostics.Ingester) *IngestHandler {
	return &IngestHandler{ingester: ingester}
}

// IngestDiagnosticsInputBody mirrors the allowlisted sender envelope plus
// the sender-stamped installation ID. Aggregation metadata survives the hop
// so repeated failures arrive with counts instead of one report per retry.
type IngestDiagnosticsInputBody struct {
	InstallationID string             `json:"installation_id" maxLength:"64" doc:"Random installation ID generated by the sending instance"`
	Version        string             `json:"version" maxLength:"64" doc:"OpenPost release reported by the sending instance"`
	Revision       string             `json:"revision" maxLength:"128" doc:"OpenPost source revision reported by the sending instance"`
	Surface        string             `json:"surface" enum:"browser,backend,worker" doc:"Surface where the failure was observed"`
	Operation      string             `json:"operation" maxLength:"160" doc:"Route template, job type, or operation name"`
	ErrorCode      string             `json:"error_code" maxLength:"64" doc:"Normalized error code from the diagnostics catalog"`
	ErrorKind      string             `json:"error_kind,omitempty" enum:"deadline_exceeded,canceled,not_found,permission_denied,connection_refused,connection_reset,unexpected_eof,dns_error,network_timeout,runtime_error,type_error,reference_error,range_error,syntax_error,quota_exceeded,security_error,not_supported,invalid_state,abort_error,network_error" doc:"Allowlisted error type, never message text"`
	HTTPMethod     string             `json:"http_method,omitempty" enum:"GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS,CONNECT,TRACE" doc:"HTTP request method, when relevant"`
	Provider       string             `json:"provider,omitempty" maxLength:"32" doc:"First-party platform, when relevant"`
	HTTPStatus     int                `json:"http_status,omitempty" minimum:"0" maximum:"599" doc:"HTTP status, when relevant"`
	RetryCount     int                `json:"retry_count,omitempty" minimum:"0" maximum:"1000000" doc:"Retry count, when relevant"`
	AttemptCount   int                `json:"attempt_count,omitempty" minimum:"0" maximum:"1000000" doc:"Attempt count, when relevant"`
	DBDriver       string             `json:"db_driver,omitempty" maxLength:"16" doc:"Normalized database driver"`
	StorageDriver  string             `json:"storage_driver,omitempty" maxLength:"16" doc:"Normalized media storage driver"`
	Occurrences    int                `json:"occurrence_count,omitempty" minimum:"0" maximum:"1000000" doc:"Aggregated occurrence count"`
	FirstSeen      string             `json:"first_seen,omitempty" maxLength:"32" doc:"RFC3339 first observation, when known"`
	LastSeen       string             `json:"last_seen,omitempty" maxLength:"32" doc:"RFC3339 last observation, when known"`
	Frames         []DiagnosticsFrame `json:"frames,omitempty" maxItems:"24" doc:"Sanitized stack frames without domains or local paths"`
}

type IngestDiagnosticsInput struct {
	Body IngestDiagnosticsInputBody
}

type IngestDiagnosticsOutput struct {
	Body struct {
		Accepted bool `json:"accepted"`
	}
}

func (h *IngestHandler) RegisterRoutes(api huma.API) {
	huma.Register(api, huma.Operation{
		OperationID:  "ingest-diagnostics",
		Method:       http.MethodPost,
		Path:         "/diagnostics/ingest",
		Summary:      "Ingest a cross-instance diagnostic report",
		Description:  "Public receiver for privacy-limited diagnostic reports sent by OpenPost instances. Strictly validated and quota-limited; accepted reports are forwarded to the maintainer channel.",
		Tags:         []string{"Diagnostics"},
		MaxBodyBytes: maxIngestHumaBodyBytes,
		Errors:       []int{400, 422, 429, 503},
	}, func(_ context.Context, input *IngestDiagnosticsInput) (*IngestDiagnosticsOutput, error) {
		return h.ingest(input)
	})
}

func (h *IngestHandler) ingest(input *IngestDiagnosticsInput) (*IngestDiagnosticsOutput, error) {
	if h == nil || h.ingester == nil || !h.ingester.IngestEnabled() {
		return nil, huma.Error503ServiceUnavailable("diagnostics ingest is not enabled")
	}
	report := diagnostics.Report{
		InstallationID:  input.Body.InstallationID,
		Version:         input.Body.Version,
		Revision:        input.Body.Revision,
		Surface:         input.Body.Surface,
		Operation:       input.Body.Operation,
		ErrorCode:       input.Body.ErrorCode,
		ErrorKind:       input.Body.ErrorKind,
		HTTPMethod:      input.Body.HTTPMethod,
		Provider:        input.Body.Provider,
		HTTPStatus:      input.Body.HTTPStatus,
		RetryCount:      input.Body.RetryCount,
		AttemptCount:    input.Body.AttemptCount,
		DBDriver:        input.Body.DBDriver,
		StorageDriver:   input.Body.StorageDriver,
		OccurrenceCount: input.Body.Occurrences,
		FirstSeen:       parseIngestTime(input.Body.FirstSeen),
		LastSeen:        parseIngestTime(input.Body.LastSeen),
	}
	for _, frame := range input.Body.Frames {
		report.Frames = append(report.Frames, diagnostics.Frame{
			Module:   frame.Module,
			Function: frame.Function,
			Line:     frame.Line,
			Column:   frame.Column,
		})
	}
	diagnostics.SanitizeReport(&report)
	if report.FirstSeen.IsZero() && report.LastSeen.IsZero() {
		// Single unaggregated reports may omit the observation window;
		// stamp ingest time rather than rejecting them.
		report.FirstSeen = time.Now().UTC()
		report.LastSeen = report.FirstSeen
	}
	if err := diagnostics.ValidateReport(report); err != nil {
		return nil, huma.Error400BadRequest("invalid diagnostic report")
	}
	if !h.ingester.Accept(report) {
		return nil, huma.Error429TooManyRequests("diagnostics quota reached; backing off")
	}
	h.ingester.ForwardAsync(report)
	output := &IngestDiagnosticsOutput{}
	output.Body.Accepted = true
	return output, nil
}

func parseIngestTime(value string) time.Time {
	if value == "" {
		return time.Time{}
	}
	parsed, err := time.Parse(time.RFC3339, value)
	if err != nil {
		return time.Time{}
	}
	return parsed.UTC()
}
