// Package repurpose suggests source-grounded clip ranges for human review.
package repurpose

import (
	"errors"
	"time"
)

const (
	maxWords                = 12000
	maxTranscriptCharacters = 180000
	maxSourceDuration       = 7200
	maxCandidates           = 3
	maxActivePerActor       = 3
	StateQueued             = "queued"
	StateAnalyzing          = "analyzing"
	StateReady              = "ready"
	StateFailed             = "failed"
	StateCancelled          = "cancelled"
)

var (
	ErrInvalid     = errors.New("invalid clip suggestion request")
	ErrNotFound    = errors.New("clip suggestions not found")
	ErrAccess      = errors.New("workspace editor access required")
	ErrConflict    = errors.New("clip suggestion revision or request conflict")
	ErrCapacity    = errors.New("too many active clip suggestion requests")
	ErrUnavailable = errors.New("clip suggestions are not configured")
	ErrLeaseActive = errors.New("clip suggestion analysis is already running")
)

type TranscriptWord struct {
	Text  string  `json:"text" minLength:"1" maxLength:"200"`
	Start float64 `json:"start" minimum:"0" maximum:"7200"`
	End   float64 `json:"end" minimum:"0" maximum:"7200"`
}

type TranscriptSource struct {
	ID              string           `json:"id" minLength:"1" maxLength:"200"`
	Revision        string           `json:"revision" minLength:"1" maxLength:"200" doc:"Caller snapshot fingerprint, not a server-verified media revision. Compare with the current source before applying."`
	MediaID         string           `json:"media_id,omitempty" maxLength:"200" doc:"Set for workspace Media sources. Access and availability are rechecked before analysis."`
	AudioTrackIndex int              `json:"audio_track_index" minimum:"0" maximum:"1000"`
	Duration        float64          `json:"duration" exclusiveMinimum:"0" maximum:"7200"`
	Words           []TranscriptWord `json:"words" minItems:"1" maxItems:"12000"`
}

type SuggestionRequest struct {
	WorkspaceID            string           `json:"workspace_id" minLength:"1" maxLength:"200"`
	Source                 TranscriptSource `json:"source"`
	Topic                  string           `json:"topic,omitempty" maxLength:"1000"`
	Audience               string           `json:"audience,omitempty" maxLength:"1000"`
	DesiredDurationSeconds int              `json:"desired_duration_seconds,omitempty" minimum:"10" maximum:"180" doc:"Preferred clip duration, not a forced length. Defaults to 45 seconds; shorter complete thoughts are allowed."`
}

type ClipCandidate struct {
	ID             string  `json:"id"`
	FirstWord      int     `json:"first_word" doc:"Inclusive zero-based index in the submitted source words."`
	LastWord       int     `json:"last_word" doc:"Inclusive zero-based index in the submitted source words."`
	Start          float64 `json:"start" doc:"Exact start of first_word in source seconds, never generated by AI."`
	End            float64 `json:"end" doc:"Exact end of last_word in source seconds, never generated by AI."`
	Title          string  `json:"title"`
	Rationale      string  `json:"rationale"`
	ContextWarning string  `json:"context_warning"`
}

type ClipSuggestions struct {
	ID             string          `json:"id"`
	WorkspaceID    string          `json:"workspace_id"`
	SourceID       string          `json:"source_id"`
	SourceRevision string          `json:"source_revision" doc:"The caller snapshot fingerprint captured at submission."`
	Revision       int             `json:"revision"`
	State          string          `json:"state" enum:"queued,analyzing,ready,failed,cancelled"`
	Candidates     []ClipCandidate `json:"candidates" maxItems:"3"`
	ErrorMessage   string          `json:"error_message,omitempty"`
	UpdatedAt      time.Time       `json:"updated_at"`
}
