import type { NativeIconPackId, NativeIconRole } from "./contract";
import { deepFreeze } from "./freeze";

const LUCIDE_ICON_ROLES: Readonly<Record<NativeIconRole, string>> = {
  add: "plus",
  back: "arrow-left",
  next: "arrow-right",
  disclosure: "chevron-right",
  close: "x",
  menu: "menu",
  more: "ellipsis",
  search: "search",
  settings: "settings",
  edit: "pencil",
  delete: "trash-2",
  check: "check",
  retry: "rotate-cw",
  calendar: "calendar-days",
  queue: "list-clock",
  videoProjects: "video",
  analytics: "chart-no-axes-combined",
  sparkles: "sparkles",
  drafts: "file-pen-line",
  workspace: "panels-top-left",
  link: "external-link",
  account: "circle-user-round",
  notification: "bell",
  undo: "undo-2",
  redo: "redo-2",
};

const HEROICON_ROLES: Readonly<Record<NativeIconRole, string>> = {
  add: "plus-circle",
  back: "arrow-long-left",
  next: "arrow-long-right",
  disclosure: "chevron-double-right",
  close: "x-circle",
  menu: "bars-3-bottom-left",
  more: "ellipsis-horizontal-circle",
  search: "magnifying-glass-circle",
  settings: "cog-6-tooth",
  edit: "pencil-square",
  delete: "trash",
  check: "check-circle",
  retry: "arrow-path-rounded-square",
  calendar: "calendar-date-range",
  queue: "queue-list",
  videoProjects: "video-camera",
  analytics: "chart-bar",
  sparkles: "sparkles",
  drafts: "document-text",
  workspace: "squares-2x2",
  link: "arrow-top-right-on-square",
  account: "user-circle",
  notification: "bell-alert",
  undo: "arrow-uturn-left",
  redo: "arrow-uturn-right",
};

export const BUILTIN_ICON_ROLE_MAPS: Readonly<
  Record<NativeIconPackId, Readonly<Record<NativeIconRole, string>>>
> = deepFreeze({
  lucide: LUCIDE_ICON_ROLES,
  "heroicons-outline": HEROICON_ROLES,
  "heroicons-solid": HEROICON_ROLES,
  phosphor: {
    add: "plus-square",
    back: "caret-circle-left",
    next: "caret-circle-right",
    disclosure: "caret-right",
    close: "x-square",
    menu: "list",
    more: "dots-three-circle",
    search: "magnifying-glass",
    settings: "gear",
    edit: "note-pencil",
    delete: "trash-simple",
    check: "seal-check",
    retry: "arrows-clockwise",
    calendar: "calendar-blank",
    queue: "queue",
    videoProjects: "video-camera",
    analytics: "chart-line-up",
    sparkles: "sparkle",
    drafts: "notebook",
    workspace: "squares-four",
    link: "arrow-square-out",
    account: "user-focus",
    notification: "bell-ringing",
    undo: "arrow-counter-clockwise",
    redo: "arrow-clockwise",
  },
  tabler: {
    add: "square-rounded-plus",
    back: "arrow-back-up",
    next: "arrow-forward-up",
    disclosure: "chevron-right",
    close: "square-rounded-x",
    menu: "menu-2",
    more: "dots-circle-horizontal",
    search: "zoom",
    settings: "adjustments-horizontal",
    edit: "edit-circle",
    delete: "trash-x",
    check: "checkbox",
    retry: "refresh-alert",
    calendar: "calendar-event",
    queue: "checklist",
    videoProjects: "video",
    analytics: "chart-line",
    sparkles: "sparkles",
    drafts: "note",
    workspace: "layout-dashboard",
    link: "external-link",
    account: "user-square-rounded",
    notification: "bell-ringing-2",
    undo: "corner-up-left",
    redo: "corner-up-right",
  },
});
